name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches: 
      - main

jobs:
  branch:
    name: Get Branch Name
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      branch_name: ${{ steps.vars.outputs.branch_name }}
    steps:
      - name: Save Branch Name
        id: vars
        run: |
          echo "branch_name=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          echo "branch_name=${{ github.head_ref }}"
  ruff:
    name: Run Ruff on the project
    needs: branch
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.branch.outputs.branch_name }}
          fetch-depth: 1
      - name: Install Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"
        
      - name: Ruff Formatter Check
        run: ruff format --check

      - name: Ruff Linter Check
        run: ruff check
    
