name: Continuous Integration

on:
    pull_request:
        branches:
            - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"
        
      - name: Ruff Linter
        run: ruff check --fix

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"

      - name: Ruff Formatter
        run: ruff format